import { WardInfo, WaterAsset, CitizenReport, SpatioTemporalCluster, AdvisoryBroadcast, BaselineComparisonMetric } from '../types';
import { calculateRiskAndPriority } from './aiIntelligence';

export const SHIVPUR_WARDS: WardInfo[] = [
  {
    id: 'ward-1',
    number: 1,
    name: 'Ward 1 - Uttar Basti',
    nameHi: 'वार्ड 1 - उत्तर बस्ती',
    population: 620,
    households: 110,
    vulnerabilityScore: 0.35,
    hasSchool: false,
    hasAnganwadi: true,
    hasHealthCenter: false,
    elevation: 'high',
    currentRiskScore: 42,
    activeComplaints: 2,
    healthFlagsCount: 0,
    status: 'moderate',
    coordinates: { lat: 25.321, lng: 82.981 },
  },
  {
    id: 'ward-2',
    number: 2,
    name: 'Ward 2 - Purana Bazar',
    nameHi: 'वार्ड 2 - पुराना बाज़ार',
    population: 890,
    households: 165,
    vulnerabilityScore: 0.40,
    hasSchool: true,
    hasAnganwadi: false,
    hasHealthCenter: false,
    elevation: 'medium',
    currentRiskScore: 28,
    activeComplaints: 1,
    healthFlagsCount: 0,
    status: 'normal',
    coordinates: { lat: 25.325, lng: 82.986 },
  },
  {
    id: 'ward-3',
    number: 3,
    name: 'Ward 3 - Talab Tola',
    nameHi: 'वार्ड 3 - तालाब टोला (संवेदनशील)',
    population: 1050,
    households: 195,
    vulnerabilityScore: 0.85, // Highly vulnerable (near pond, low-lying, anganwadi + primary school)
    hasSchool: true,
    hasAnganwadi: true,
    hasHealthCenter: true,
    elevation: 'low_lying',
    currentRiskScore: 89,
    activeComplaints: 6,
    healthFlagsCount: 4,
    status: 'high_risk',
    coordinates: { lat: 25.318, lng: 82.978 },
  },
  {
    id: 'ward-4',
    number: 4,
    name: 'Ward 4 - Harijan Basti',
    nameHi: 'वार्ड 4 - दक्षिण बस्ती',
    population: 740,
    households: 130,
    vulnerabilityScore: 0.70,
    hasSchool: false,
    hasAnganwadi: true,
    hasHealthCenter: false,
    elevation: 'low_lying',
    currentRiskScore: 68,
    activeComplaints: 3,
    healthFlagsCount: 2,
    status: 'high_risk',
    coordinates: { lat: 25.314, lng: 82.983 },
  },
  {
    id: 'ward-5',
    number: 5,
    name: 'Ward 5 - Paschim Dih',
    nameHi: 'वार्ड 5 - पश्चिम डीह',
    population: 580,
    households: 95,
    vulnerabilityScore: 0.25,
    hasSchool: false,
    hasAnganwadi: false,
    hasHealthCenter: false,
    elevation: 'high',
    currentRiskScore: 35,
    activeComplaints: 1,
    healthFlagsCount: 0,
    status: 'normal',
    coordinates: { lat: 25.323, lng: 82.972 },
  },
  {
    id: 'ward-6',
    number: 6,
    name: 'Ward 6 - Naya Kheda',
    nameHi: 'वार्ड 6 - नया खेड़ा',
    population: 610,
    households: 105,
    vulnerabilityScore: 0.30,
    hasSchool: false,
    hasAnganwadi: true,
    hasHealthCenter: false,
    elevation: 'medium',
    currentRiskScore: 22,
    activeComplaints: 0,
    healthFlagsCount: 0,
    status: 'normal',
    coordinates: { lat: 25.329, lng: 82.976 },
  },
];

export const SHIVPUR_ASSETS: WaterAsset[] = [
  {
    id: 'asset-hp-01',
    name: 'Deep Borewell India Mark II Handpump #1',
    nameHi: 'इंडिया मार्क-II हैंडपंप #1 (स्कूल के पास)',
    type: 'handpump',
    wardId: 'ward-3',
    qrCode: 'SHIV-HP-01',
    locationDescription: 'Adjacent to Primary School Playground, Talab Tola',
    installYear: 2021,
    failureCount: 4,
    lastInspectionDate: '2026-08-14',
    coordinates: { lat: 25.3184, lng: 82.9782 },
  },
  {
    id: 'asset-hp-02',
    name: 'Community Handpump #2 (Temple Chowk)',
    nameHi: 'हैंडपंप #2 (शिव मंदिर चौक)',
    type: 'handpump',
    wardId: 'ward-2',
    qrCode: 'SHIV-HP-02',
    locationDescription: 'Shiv Mandir Chowk, Main Bazaar',
    installYear: 2023,
    failureCount: 1,
    lastInspectionDate: '2026-09-02',
    coordinates: { lat: 25.3252, lng: 82.9861 },
  },
  {
    id: 'asset-hp-03',
    name: 'Handpump #3 (Harijan Basti Wells)',
    nameHi: 'हैंडपंप #3 (आंगनवाड़ी के सामने)',
    type: 'handpump',
    wardId: 'ward-4',
    qrCode: 'SHIV-HP-03',
    locationDescription: 'Opposite Anganwadi Centre 4',
    installYear: 2020,
    failureCount: 3,
    lastInspectionDate: '2026-07-20',
    coordinates: { lat: 25.3142, lng: 82.9829 },
  },
  {
    id: 'asset-oht-01',
    name: 'Gram Panchayat Overhead Water Tank 50kL',
    nameHi: 'ग्राम पंचायत ओवरहेड पानी टंकी (50 हजार ली.)',
    type: 'overhead_tank',
    wardId: 'ward-1',
    qrCode: 'SHIV-OHT-01',
    locationDescription: 'Panchayat Bhawan Compound, Uttar Basti',
    installYear: 2019,
    failureCount: 1,
    lastInspectionDate: '2026-09-10',
    coordinates: { lat: 25.3215, lng: 82.9812 },
  },
  {
    id: 'asset-pipe-01',
    name: 'Main Feeder Pipeline 100mm PVC',
    nameHi: 'मुख्य फीडर पाइपलाइन 100mm',
    type: 'pipeline',
    wardId: 'ward-1',
    qrCode: 'SHIV-PIPE-01',
    locationDescription: 'Along Road from Booster Pump to Ward 3 junction',
    installYear: 2022,
    failureCount: 2,
    lastInspectionDate: '2026-08-30',
    coordinates: { lat: 25.3201, lng: 82.9805 },
  },
  {
    id: 'asset-tap-01',
    name: 'Public Standpost #4 (Community Well Area)',
    nameHi: 'सार्वजनिक नल स्टैंडपोस्ट #4',
    type: 'public_tap',
    wardId: 'ward-5',
    qrCode: 'SHIV-TAP-01',
    locationDescription: 'West Junction near Panchayat Well',
    installYear: 2024,
    failureCount: 0,
    lastInspectionDate: '2026-09-12',
    coordinates: { lat: 25.3228, lng: 82.9719 },
  },
];

// Generate initial rich mock reports
export function getInitialReports(): CitizenReport[] {
  const ward3 = SHIVPUR_WARDS.find(w => w.id === 'ward-3')!;
  const ward1 = SHIVPUR_WARDS.find(w => w.id === 'ward-1')!;
  const ward4 = SHIVPUR_WARDS.find(w => w.id === 'ward-4')!;
  const ward2 = SHIVPUR_WARDS.find(w => w.id === 'ward-2')!;

  const assetHp1 = SHIVPUR_ASSETS.find(a => a.id === 'asset-hp-01');
  const assetPipe1 = SHIVPUR_ASSETS.find(a => a.id === 'asset-pipe-01');

  // Report 1: Critical cluster trigger in Ward 3
  const text1 = 'हैंडपंप से पीला और बदबूदार पानी निकल रहा है। हमारे घर में दो बच्चों को उल्टी-दस्त हो गया है।';
  const risk1 = calculateRiskAndPriority({
    category: 'illness_cluster',
    text: text1,
    healthFlag: true,
    affectedHouseholds: 35,
    ward: ward3,
    asset: assetHp1,
    recentRainfallMm: 45,
    corroboratingReportsCount: 4,
    reporterTrustScore: 0.92,
    daysOpen: 2,
  });

  const report1: CitizenReport = {
    id: 'rep-101',
    reporterHash: 'usr_f89a2b',
    reporterName: 'रामेश्वर प्रसाद (वार्ड 3)',
    wardId: 'ward-3',
    assetId: 'asset-hp-01',
    category: 'illness_cluster',
    text: text1,
    transcript: 'paani me peela aur badbu aa rahi hai, do baccho ko ulti dast hua hai school ke bagal me',
    language: 'hi',
    healthFlag: true,
    affectedHouseholdsCount: 35,
    trustScore: 0.92,
    status: 'under_review',
    createdAt: '2 घंटे पहले (10:15 AM)',
    isOfflineDraft: false,
    riskScores: risk1,
    clusterId: 'cluster-talab-01',
    assignedTo: 'विनोद कुमार (जल मिस्त्री)',
    assignedAt: '1 घंटे पहले',
    slaDueHours: 4,
    isEscalated: false,
  };

  // Report 2: Corroborating report in Ward 3 near Primary School
  const text2 = 'Primary school handpump water smells metallic and taste is bitter. Anganwadi kids refused to drink.';
  const risk2 = calculateRiskAndPriority({
    category: 'smell_colour',
    text: text2,
    healthFlag: true,
    affectedHouseholds: 45,
    ward: ward3,
    asset: assetHp1,
    recentRainfallMm: 45,
    corroboratingReportsCount: 4,
    reporterTrustScore: 0.95,
    daysOpen: 1,
  });

  const report2: CitizenReport = {
    id: 'rep-102',
    reporterHash: 'usr_d41c99',
    reporterName: 'सुनीता देवी (आंगनवाड़ी सहायिका)',
    wardId: 'ward-3',
    assetId: 'asset-hp-01',
    category: 'smell_colour',
    text: text2,
    transcript: text2,
    language: 'en',
    healthFlag: true,
    affectedHouseholdsCount: 45,
    trustScore: 0.95,
    status: 'assigned',
    createdAt: '3 घंटे पहले (09:30 AM)',
    isOfflineDraft: false,
    riskScores: risk2,
    clusterId: 'cluster-talab-01',
    assignedTo: 'विनोद कुमार (जल मिस्त्री)',
    assignedAt: '2 घंटे पहले',
    slaDueHours: 4,
  };

  // Report 3: Pipeline burst in Ward 1
  const text3 = 'सड़क के किनारे मुख्य पाइप फट गया है। हजारों लीटर पानी बह रहा है और गंदा पानी पाइप में जा रहा है।';
  const risk3 = calculateRiskAndPriority({
    category: 'leakage',
    text: text3,
    healthFlag: false,
    affectedHouseholds: 50,
    ward: ward1,
    asset: assetPipe1,
    recentRainfallMm: 45,
    corroboratingReportsCount: 2,
    reporterTrustScore: 0.88,
    daysOpen: 1,
  });

  const report3: CitizenReport = {
    id: 'rep-103',
    reporterHash: 'usr_8b21ef',
    reporterName: 'महेश कुमार यादव',
    wardId: 'ward-1',
    assetId: 'asset-pipe-01',
    category: 'leakage',
    text: text3,
    transcript: text3,
    language: 'hi',
    healthFlag: false,
    affectedHouseholdsCount: 50,
    trustScore: 0.88,
    status: 'assigned',
    createdAt: '4 घंटे पहले (08:45 AM)',
    isOfflineDraft: false,
    riskScores: risk3,
    assignedTo: 'सुरेश यादव (प्लम्बर दल)',
    slaDueHours: 8,
  };

  // Report 4: Ward 4 Low supply
  const text4 = 'Ward 4 handpump handle is loose and pumping air after only 2 buckets. Groundwater level dropped.';
  const risk4 = calculateRiskAndPriority({
    category: 'handpump_failure',
    text: text4,
    healthFlag: false,
    affectedHouseholds: 18,
    ward: ward4,
    recentRainfallMm: 45,
    corroboratingReportsCount: 1,
    reporterTrustScore: 0.82,
    daysOpen: 3,
  });

  const report4: CitizenReport = {
    id: 'rep-104',
    reporterHash: 'usr_7a39df',
    reporterName: 'कलावती देवी',
    wardId: 'ward-4',
    assetId: 'asset-hp-03',
    category: 'handpump_failure',
    text: text4,
    transcript: text4,
    language: 'en',
    healthFlag: false,
    affectedHouseholdsCount: 18,
    trustScore: 0.82,
    status: 'pending',
    createdAt: '1 दिन पहले',
    isOfflineDraft: false,
    riskScores: risk4,
  };

  // Report 5: Resolved issue in Ward 2 with citizen confirmation
  const text5 = 'सार्वजनिक नल की टोटी से गंदा पानी आ रहा था।';
  const risk5 = calculateRiskAndPriority({
    category: 'smell_colour',
    text: text5,
    healthFlag: false,
    affectedHouseholds: 12,
    ward: ward2,
    recentRainfallMm: 45,
    corroboratingReportsCount: 1,
    reporterTrustScore: 0.85,
    daysOpen: 5,
  });

  const report5: CitizenReport = {
    id: 'rep-105',
    reporterHash: 'usr_2398ab',
    reporterName: 'दिलीप सिंह',
    wardId: 'ward-2',
    category: 'smell_colour',
    text: text5,
    language: 'hi',
    healthFlag: false,
    affectedHouseholdsCount: 12,
    trustScore: 0.85,
    status: 'resolved',
    createdAt: '3 दिन पहले',
    isOfflineDraft: false,
    riskScores: risk5,
    assignedTo: 'विनोद कुमार',
    inspectionNotes: 'पाइपलाइन फ्लश की गई और ब्लीचिंग पाउडर से क्लोरीनेशन किया गया। पानी अब पूरी तरह साफ व गंधहीन है।',
    resolvedAt: 'कल शाम 5:00 बजे',
    citizenConfirmed: true,
    citizenComment: 'काम बढ़िया हुआ, अब पानी एकदम साफ आ रहा है। धन्यवाद पंचायत टीम।',
  };

  return [report1, report2, report3, report4, report5];
}

export const INITIAL_CLUSTERS: SpatioTemporalCluster[] = [
  {
    id: 'cluster-talab-01',
    wardId: 'ward-3',
    wardName: 'Ward 3 - Talab Tola',
    title: 'Biological Contamination & Waterborne Illness Outbreak Spike',
    titleHi: 'संभावित जलजनित संक्रमण एवं संदूषण क्लस्टर',
    reportIds: ['rep-101', 'rep-102'],
    healthCasesCount: 5,
    detectedAt: 'आज सुबह 10:20 बजे (AI द्वारा चिन्हित)',
    clusterScore: 94,
    status: 'active',
    primaryIssue: 'illness_cluster',
    summaryHi: 'तालाब टोला में पिछले 24 घंटों में 6 शिकायतें व 4 घरों में डायरिया के मामले सामने आए हैं। हालिया वर्षा जल रिसाव मुख्य कारण प्रतीत हो रहा है।',
    summaryEn: '6 reports and 4 household illness flags detected in Talab Tola within 24 hours. Elevated turbidity and microbiological risk following heavy rainfall.',
  },
];

export const INITIAL_ADVISORIES: AdvisoryBroadcast[] = [
  {
    id: 'adv-01',
    wardId: 'ward-3',
    wardName: 'Ward 3 - Talab Tola',
    title: 'Water Safety Alert — Boil Before Drinking',
    textHi: 'ग्राम पंचायत शिवपुर सूचना: वार्ड 3 (तालाब टोला) के सभी निवासी ध्यान दें! हैंडपंप #1 के पानी में संदूषण की आशंका है। कृपया पानी को 10 मिनट उबालकर ही पिएं। जांच दल मौके पर है।',
    textEn: 'Gram Panchayat Shivpur Advisory: Residents of Ward 3 (Talab Tola), Handpump #1 water under inspection. Please boil all drinking water for at least 10 minutes.',
    approvedBy: 'सरपंच श्रीमती शांति देवी',
    sentAt: '10:45 AM (SMS & लाउडस्पीकर द्वारा प्रसारित)',
    channel: 'speaker',
  },
];

export const BASELINE_EVALUATION_METRICS: BaselineComparisonMetric[] = [
  {
    metricName: 'Detection Lead Time (Earliest Outbreak Warning)',
    description: 'Hours before village complaint surge triggers conventional intervention',
    baselineValue: '48.2 Hours (after clinic rush)',
    jalRakshakValue: '14.0 Hours (early signals + rain)',
    improvement: '⚡ 34.2 Hours Earlier Warning',
  },
  {
    metricName: 'Top-5 Priority Hit Rate (NDCG@5)',
    description: 'Ranking accuracy of truly hazardous issues at the top of the queue',
    baselineValue: '0.46 (Chronological FIFO queue)',
    jalRakshakValue: '0.89 (Multi-factor risk scoring)',
    improvement: '+93% Prioritization Accuracy',
  },
  {
    metricName: 'Precision on High-Risk Outbreak Clusters',
    description: 'Accurate identification of real biological contamination events without false panic',
    baselineValue: '58.0% (Single complaint threshold)',
    jalRakshakValue: '91.4% (Multi-source corroboration)',
    improvement: '+33.4% Fewer False Alarms',
  },
  {
    metricName: 'Offline Reporting Accessibility',
    description: 'Percentage of rural complaints successfully captured without active cellular signal',
    baselineValue: '12% (Traditional online forms)',
    jalRakshakValue: '99.5% (IndexedDB + PWA offline drafts)',
    improvement: '+87.5% Greater Inclusivity',
  },
  {
    metricName: 'Model Calibration (Brier Score)',
    description: 'Calibration accuracy of confidence indicators (lower is better, 0.00 is perfect)',
    baselineValue: '0.28 (Uncalibrated heuristic)',
    jalRakshakValue: '0.08 (Calibrated risk weights)',
    improvement: '3.5x More Reliable Confidence',
  },
];
